[package]
name = "charstat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive", "wrap_help"] }
rand = "0.8.5"
squirrel-rng = "0.2.1"
